import type {
  Subscriber,
  Specialist,
  DashboardStats,
  Notification,
  PendingRequest,
} from "./types"

export const dashboardStats: DashboardStats = {
  totalSubscribers: 248,
  activeSubscribers: 189,
  totalSpecialists: 12,
  monthlyRevenue: 45600,
  newSubscribersThisMonth: 34,
  expiringSubscriptions: 18,
  averageBmi: 26.4,
  subscriberGrowth: 12.5,
}

export const subscribers: Subscriber[] = [
  {
    id: "sub-001",
    name: "أحمد محمد العلي",
    email: "ahmed@example.com",
    phone: "+962791234567",
    role: "subscriber",
    gender: "male",
    age: 28,
    height: 175,
    weight: 85,
    targetWeight: 75,
    activityLevel: "moderate",
    healthConditions: ["ضغط دم مرتفع"],
    allergies: ["لاكتوز"],
    subscriptionPlan: "premium",
    subscriptionStatus: "active",
    subscriptionStart: "2026-01-01",
    subscriptionEnd: "2026-04-01",
    assignedNutritionist: "spec-001",
    assignedTrainer: "spec-003",
    bmi: 27.8,
    dailyCalories: 2200,
    waterTarget: 3,
    createdAt: "2026-01-01",
  },
  {
    id: "sub-002",
    name: "سارة خالد الحسن",
    email: "sara@example.com",
    phone: "+962797654321",
    role: "subscriber",
    gender: "female",
    age: 32,
    height: 162,
    weight: 70,
    targetWeight: 60,
    activityLevel: "light",
    healthConditions: [],
    allergies: ["غلوتين"],
    subscriptionPlan: "vip",
    subscriptionStatus: "active",
    subscriptionStart: "2025-12-15",
    subscriptionEnd: "2026-06-15",
    assignedNutritionist: "spec-001",
    assignedTrainer: "spec-004",
    bmi: 26.7,
    dailyCalories: 1800,
    waterTarget: 2.5,
    createdAt: "2025-12-15",
  },
  {
    id: "sub-003",
    name: "محمد يوسف الكردي",
    email: "mohammad@example.com",
    phone: "+962785551234",
    role: "subscriber",
    gender: "male",
    age: 45,
    height: 180,
    weight: 95,
    targetWeight: 82,
    activityLevel: "sedentary",
    healthConditions: ["سكري نوع 2", "كوليسترول"],
    allergies: [],
    subscriptionPlan: "vip",
    subscriptionStatus: "active",
    subscriptionStart: "2025-11-01",
    subscriptionEnd: "2026-05-01",
    assignedNutritionist: "spec-002",
    assignedTrainer: "spec-003",
    bmi: 29.3,
    dailyCalories: 1900,
    waterTarget: 3.5,
    createdAt: "2025-11-01",
  },
  {
    id: "sub-004",
    name: "نور الدين العمري",
    email: "nour@example.com",
    phone: "+962791112233",
    role: "subscriber",
    gender: "male",
    age: 22,
    height: 170,
    weight: 65,
    targetWeight: 72,
    activityLevel: "active",
    healthConditions: [],
    allergies: [],
    subscriptionPlan: "basic",
    subscriptionStatus: "active",
    subscriptionStart: "2026-02-01",
    subscriptionEnd: "2026-03-01",
    assignedNutritionist: "spec-002",
    bmi: 22.5,
    dailyCalories: 2800,
    waterTarget: 3,
    createdAt: "2026-02-01",
  },
  {
    id: "sub-005",
    name: "ليلى أحمد الزعبي",
    email: "layla@example.com",
    phone: "+962789998877",
    role: "subscriber",
    gender: "female",
    age: 38,
    height: 158,
    weight: 78,
    targetWeight: 65,
    activityLevel: "light",
    healthConditions: ["مشاكل في الغدة الدرقية"],
    allergies: ["بيض"],
    subscriptionPlan: "premium",
    subscriptionStatus: "expired",
    subscriptionStart: "2025-10-01",
    subscriptionEnd: "2026-01-01",
    assignedNutritionist: "spec-001",
    assignedTrainer: "spec-004",
    bmi: 31.2,
    dailyCalories: 1600,
    waterTarget: 2.5,
    createdAt: "2025-10-01",
  },
  {
    id: "sub-006",
    name: "عمر حسام الطراونة",
    email: "omar@example.com",
    phone: "+962781234567",
    role: "subscriber",
    gender: "male",
    age: 35,
    height: 182,
    weight: 88,
    targetWeight: 80,
    activityLevel: "moderate",
    healthConditions: [],
    allergies: ["مكسرات"],
    subscriptionPlan: "premium",
    subscriptionStatus: "active",
    subscriptionStart: "2026-01-15",
    subscriptionEnd: "2026-04-15",
    assignedNutritionist: "spec-002",
    assignedTrainer: "spec-003",
    bmi: 26.6,
    dailyCalories: 2400,
    waterTarget: 3,
    createdAt: "2026-01-15",
  },
  {
    id: "sub-007",
    name: "هنادي فارس القاسم",
    email: "hanadi@example.com",
    phone: "+962795556677",
    role: "subscriber",
    gender: "female",
    age: 27,
    height: 165,
    weight: 58,
    targetWeight: 55,
    activityLevel: "active",
    healthConditions: [],
    allergies: [],
    subscriptionPlan: "basic",
    subscriptionStatus: "trial",
    subscriptionStart: "2026-02-05",
    subscriptionEnd: "2026-02-19",
    bmi: 21.3,
    dailyCalories: 2000,
    waterTarget: 2.5,
    createdAt: "2026-02-05",
  },
  {
    id: "sub-008",
    name: "خالد ابراهيم النعيمات",
    email: "khaled@example.com",
    phone: "+962787778899",
    role: "subscriber",
    gender: "male",
    age: 50,
    height: 172,
    weight: 102,
    targetWeight: 85,
    activityLevel: "sedentary",
    healthConditions: ["ضغط دم مرتفع", "سكري نوع 2"],
    allergies: ["لاكتوز", "غلوتين"],
    subscriptionPlan: "vip",
    subscriptionStatus: "suspended",
    subscriptionStart: "2025-09-01",
    subscriptionEnd: "2026-03-01",
    assignedNutritionist: "spec-001",
    assignedTrainer: "spec-003",
    bmi: 34.5,
    dailyCalories: 1700,
    waterTarget: 3.5,
    createdAt: "2025-09-01",
  },
]

export const specialists: Specialist[] = [
  {
    id: "spec-001",
    name: "د. رنا عبدالله الخطيب",
    email: "rana@example.com",
    phone: "+962791001001",
    role: "nutritionist",
    specialization: "تغذية علاجية",
    bio: "أخصائية تغذية معتمدة مع خبرة 8 سنوات في التغذية العلاجية وادارة الوزن",
    experience: 8,
    rating: 4.8,
    activeSubscribers: 32,
    maxSubscribers: 40,
    availability: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    createdAt: "2024-06-01",
  },
  {
    id: "spec-002",
    name: "د. فادي محمود الصالح",
    email: "fadi@example.com",
    phone: "+962792002002",
    role: "nutritionist",
    specialization: "تغذية رياضية",
    bio: "متخصص في التغذية الرياضية وبناء الأجسام مع خبرة 6 سنوات",
    experience: 6,
    rating: 4.6,
    activeSubscribers: 28,
    maxSubscribers: 35,
    availability: ["الأحد", "الاثنين", "الأربعاء", "الخميس"],
    createdAt: "2024-09-01",
  },
  {
    id: "spec-003",
    name: "كابتن باسل حمدان",
    email: "bassel@example.com",
    phone: "+962793003003",
    role: "trainer",
    specialization: "تدريب القوة واللياقة",
    bio: "مدرب لياقة بدنية معتمد مع خبرة 10 سنوات في تدريب القوة والتحمل",
    experience: 10,
    rating: 4.9,
    activeSubscribers: 45,
    maxSubscribers: 50,
    availability: [
      "الأحد",
      "الاثنين",
      "الثلاثاء",
      "الأربعاء",
      "الخميس",
      "السبت",
    ],
    createdAt: "2024-03-01",
  },
  {
    id: "spec-004",
    name: "كابتن دانا يوسف",
    email: "dana@example.com",
    phone: "+962794004004",
    role: "trainer",
    specialization: "يوغا وتمارين مرونة",
    bio: "مدربة يوغا ومرونة معتمدة مع خبرة 5 سنوات",
    experience: 5,
    rating: 4.7,
    activeSubscribers: 22,
    maxSubscribers: 30,
    availability: ["الاثنين", "الثلاثاء", "الأربعاء", "الجمعة", "السبت"],
    createdAt: "2025-01-01",
  },
]

export const notifications: Notification[] = [
  {
    id: "notif-001",
    title: "اشتراك جديد",
    message: "تم تسجيل مشترك جديد: هنادي فارس القاسم - باقة تجريبية",
    type: "success",
    read: false,
    createdAt: "2026-02-11T10:30:00",
  },
  {
    id: "notif-002",
    title: "اشتراك منتهي",
    message: "انتهى اشتراك ليلى أحمد الزعبي - يرجى المتابعة",
    type: "warning",
    read: false,
    createdAt: "2026-02-11T09:15:00",
  },
  {
    id: "notif-003",
    title: "تقييم جديد",
    message: "حصل كابتن باسل حمدان على تقييم 5 نجوم من أحمد محمد",
    type: "info",
    read: true,
    createdAt: "2026-02-10T16:45:00",
  },
  {
    id: "notif-004",
    title: "اشتراك معلق",
    message: "تم تعليق اشتراك خالد ابراهيم النعيمات - عدم الدفع",
    type: "error",
    read: false,
    createdAt: "2026-02-10T14:00:00",
  },
  {
    id: "notif-005",
    title: "تحديث خطة غذائية",
    message: "قامت د. رنا بتحديث الخطة الغذائية لـ سارة خالد الحسن",
    type: "info",
    read: true,
    createdAt: "2026-02-09T11:30:00",
  },
  {
    id: "notif-006",
    title: "طلب اشتراك جديد",
    message: "محمد سمير يريد الاشتراك في باقة بريميوم",
    type: "info",
    read: false,
    createdAt: "2026-02-08T09:00:00",
  },
  {
    id: "notif-007",
    title: "تقرير أسبوعي جاهز",
    message: "تقرير أداء الأخصائيين للأسبوع الثاني من فبراير جاهز للمراجعة",
    type: "success",
    read: true,
    createdAt: "2026-02-07T18:00:00",
  },
  {
    id: "notif-008",
    title: "هدف محقق",
    message: "أحمد محمد العلي وصل لهدف الوزن المطلوب - خسارة 5 كجم",
    type: "success",
    read: true,
    createdAt: "2026-02-07T10:00:00",
  },
  {
    id: "notif-009",
    title: "تنبيه سعة أخصائي",
    message: "كابتن باسل حمدان وصل لـ 90% من الحد الأقصى للمشتركين",
    type: "warning",
    read: false,
    createdAt: "2026-02-06T14:30:00",
  },
  {
    id: "notif-010",
    title: "مشترك لم يسجل دخول",
    message: "عمر حسام الطراونة لم يسجل دخول منذ 7 أيام",
    type: "warning",
    read: true,
    createdAt: "2026-02-05T08:00:00",
  },
]

export const monthlyRevenueData = [
  { month: "سبتمبر", revenue: 32000, subscribers: 165 },
  { month: "أكتوبر", revenue: 35000, subscribers: 178 },
  { month: "نوفمبر", revenue: 38500, subscribers: 195 },
  { month: "ديسمبر", revenue: 41000, subscribers: 210 },
  { month: "يناير", revenue: 43200, subscribers: 230 },
  { month: "فبراير", revenue: 45600, subscribers: 248 },
]

export const subscriptionDistribution = [
  { name: "أساسي", value: 85, color: "hsl(var(--chart-3))" },
  { name: "بريميوم", value: 108, color: "hsl(var(--chart-1))" },
  { name: "VIP", value: 55, color: "hsl(var(--chart-2))" },
]

export const planPrices = {
  basic: { monthly: 150, name: "أساسي", features: ["خطة غذائية", "متابعة أسبوعية", "تطبيق الجوال"] },
  premium: {
    monthly: 300,
    name: "بريميوم",
    features: ["خطة غذائية مخصصة", "خطة تمارين", "متابعة يومية", "محادثة مع الأخصائي", "تطبيق الجوال"],
  },
  vip: {
    monthly: 500,
    name: "VIP",
    features: [
      "خطة غذائية مخصصة",
      "خطة تمارين مخصصة",
      "متابعة يومية",
      "محادثة مع الأخصائي والمدرب",
      "تقارير أسبوعية مفصلة",
      "أولوية في المواعيد",
      "تطبيق الجوال",
    ],
  },
}

export const pendingRequests: PendingRequest[] = [
  {
    id: "req-001",
    name: "د. سلمى ناصر الحربي",
    email: "salma@example.com",
    phone: "+962796001001",
    gender: "female",
    role: "nutritionist",
    specialization: "تغذية أطفال",
    experience: 4,
    bio: "أخصائية تغذية أطفال مع خبرة في التعامل مع حالات سوء التغذية والحساسية الغذائية عند الأطفال",
    workingHours: "9:00 ص - 3:00 م",
    availableDays: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء"],
    maxSubscribers: 25,
    certificates: ["شهادة_تغذية_اطفال.pdf", "بكالوريوس_تغذية.pdf"],
    status: "pending",
    submittedAt: "2026-02-10T14:30:00",
  },
  {
    id: "req-002",
    name: "كابتن معاذ وليد الشمري",
    email: "muath@example.com",
    phone: "+962797002002",
    gender: "male",
    role: "trainer",
    specialization: "كروس فيت وتمارين وظيفية",
    experience: 7,
    bio: "مدرب كروس فيت معتمد دوليا مع خبرة في تدريب الرياضيين المحترفين وبرامج اعادة التأهيل الرياضي",
    workingHours: "6:00 ص - 12:00 م",
    availableDays: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "السبت"],
    maxSubscribers: 40,
    certificates: ["كروس_فيت_L3.pdf", "اعادة_تأهيل_رياضي.pdf", "اسعافات_اولية.pdf"],
    status: "pending",
    submittedAt: "2026-02-08T09:15:00",
  },
  {
    id: "req-003",
    name: "د. ياسمين طارق العبادي",
    email: "yasmin@example.com",
    phone: "+962798003003",
    gender: "female",
    role: "nutritionist",
    specialization: "تغذية رياضية وبناء أجسام",
    experience: 3,
    bio: "حاصلة على ماجستير تغذية رياضية، متخصصة في وضع خطط غذائية لبناء العضلات وتحسين الأداء الرياضي",
    workingHours: "10:00 ص - 6:00 م",
    availableDays: ["الأحد", "الثلاثاء", "الخميس"],
    maxSubscribers: 20,
    certificates: ["ماجستير_تغذية_رياضية.pdf"],
    status: "pending",
    submittedAt: "2026-02-12T11:00:00",
  },
  {
    id: "req-004",
    name: "كابتن زيد سامي الرواشدة",
    email: "zaid@example.com",
    phone: "+962799004004",
    gender: "male",
    role: "trainer",
    specialization: "سباحة ورياضات مائية",
    experience: 9,
    bio: "مدرب سباحة معتمد من الاتحاد الدولي، بطل سابق في السباحة على مستوى المملكة",
    workingHours: "7:00 ص - 1:00 م",
    availableDays: ["الأحد", "الاثنين", "الأربعاء", "الخميس", "السبت"],
    maxSubscribers: 30,
    certificates: ["مدرب_سباحة_دولي.pdf", "انقاذ_بحري.pdf"],
    status: "pending",
    submittedAt: "2026-02-06T08:45:00",
  },
  {
    id: "req-005",
    name: "د. هالة عبدالرحمن المصري",
    email: "hala@example.com",
    phone: "+962791005005",
    gender: "female",
    role: "nutritionist",
    specialization: "تغذية مرضى السكري",
    experience: 11,
    bio: "دكتوراة في التغذية السريرية مع تركيز على ادارة مرض السكري من النوع الأول والثاني عبر النظام الغذائي",
    workingHours: "8:00 ص - 2:00 م",
    availableDays: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس"],
    maxSubscribers: 35,
    certificates: ["دكتوراة_تغذية_سريرية.pdf", "شهادة_CDE.pdf", "بورد_تغذية.pdf"],
    status: "pending",
    submittedAt: "2026-02-13T15:20:00",
  },
]